/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 18 พ.ค. 2554, 0:38:57
 */
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.sql.rowset.FilteredRowSet;
import javax.swing.JCheckBox;
import javax.swing.DefaultCellEditor;
/**
 *
 * @author SamSung
 */
public class NewJDialog extends javax.swing.JDialog {

    /** Creates new form NewJDialog */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         aa();
    }
public static void aa(){
      String code = "";
                    String desc = "";
                    String detail = "";
                    String rate = "";
                    String unit = "";
                    String curtype = "";
                    String QueryString1 = "";
                    String sql, publish = "";
                    String[] ar = new String[100];
        String path="D:\\FrontWeb\\web";
String user1="root";
String pw="test";
String url="jdbc:postgresql://localhost:5432/front";
String driver="org.postgresql.Driver";
String id ="";
          Statement stmt = null;
                    ResultSet rs = null;
                    Connection con = null;


                    //  if (request.getParameter("submit") != null) {

                    try {

                     Class.forName("org.postgresql.Driver");
                        con = DriverManager.getConnection(url, user1, pw);
                    } catch (Exception ex) {

                        System.out.println("exeSQL Error : " + ex.getMessage());
                    }id="qq";
                      try {
                     stmt = con.createStatement();
                            QueryString1 = "Select * FROM currency WHERE cr_Id ='" + id + "'";
                            rs = stmt.executeQuery(QueryString1);
                            while (rs.next()) {
                                code = rs.getString(1);
                                desc = rs.getString(2);
                                detail = rs.getString(3);
                                rate = rs.getString(4);
                                unit = rs.getString(5);
                                curtype = rs.getString(6).trim();;
                            }  } catch (Exception ex) {
                            System.out.println("exeSQL Error : " + ex.getMessage());
                        }System.out.println(curtype);
                        String j="t1";
                    if(curtype==j){System.out.println("selected");}
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
